### ISSUE TITLE
deploy nodejs redis app by using aws copilot

### ISSUE THREAD

**Issue by asifmai** [aws/copilot-cli#2211]
I have a nodejs express app which uses redis. I am using aws copilot cli to deploy this app to aws ecs.

I first initialez the app using

`copilot app init`
Then I initialized an evironment using

`copilot env init`
using the defaults.

After that I created a service for redis using:

`copilot init -t Backend\ Service --image redis --port 6379 --name redis`
I deployed the service and got the namespace as:

`redis.test-app.local`
In my application .env file I added it like this:

```
REDIS_PORT=6379
REDIS_IP=http://redis.test-app.local
```
Then I created a service for my express app using the following Docker file:

```
FROM node:14
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "development"]
```
When I deploy the app It fails with the following errors

`failed to create: [PublicLoadBalancer]`
`failed to update: [ServiceDiscoveryNameSpace]`

I think i'm referencing to the redis service the wrong way.
I need help linking my nodejs load balancer service with redis backend service

**Comment by efekarakus** [comment]
Hi @asifmai 

That's very strange! Are there any additional details on why the `PublicLoadBalancer` and `ServiceDiscoveryNameSpace` failed to create in the CloudFormation console?

Just to make sure the `redis` "Backend Service" is deployed first successfully with `deploy`, and the failure happens when you try to deploy your new Load Balanced Web Service?

I wonder if this blog post from Maarten would help: https://maartenbruntink.nl/blog/2020/08/16/deploying-containers-with-the-aws-copilot-cli-part-1/ where he deploys also a backend redis service along with a load balanced web service.

**Comment by asifmai** [comment]
I have followed the link that you provided to add multiple services it still does not work.
When I go to the logs it shows me all services deleted
And yes redis is deployed successfully as a backend service and then the app deployment as a service fails

**Comment by asifmai** [comment]
about the cloudwatch logs. I'm getting these errors:

2021-04-26T00:25:37.287+05:00 | > backend@0.0.0 development /usr/src/app
  | 2021-04-26T00:25:37.287+05:00 | > NODE_ENV=development node ./bin/www
  | 2021-04-26T00:25:42.101+05:00 | key-asdf
  | 2021-04-26T00:25:44.107+05:00 | (node:33) DeprecationWarning: `openSet()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client
  | 2021-04-26T00:25:44.107+05:00 | (Use `node --trace-deprecation ...` to show where the warning was created)
  | 2021-04-26T00:25:44.107+05:00 | (node:33) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
  | 2021-04-26T00:25:44.202+05:00 | events.js:292
  | 2021-04-26T00:25:44.202+05:00 | throw er; // Unhandled 'error' event
  | 2021-04-26T00:25:44.202+05:00 | ^
  | 2021-04-26T00:25:44.202+05:00 | Error: getaddrinfo ENOTFOUND redis://redis.adioone-teams.local
  | 2021-04-26T00:25:44.202+05:00 | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  | 2021-04-26T00:25:44.202+05:00 | Emitted 'error' event on RedisClient instance at:
  | 2021-04-26T00:25:44.202+05:00 | at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:342:14)
  | 2021-04-26T00:25:44.202+05:00 | at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:223:14)
  | 2021-04-26T00:25:44.202+05:00 | at Socket.emit (events.js:315:20)
  | 2021-04-26T00:25:44.202+05:00 | at emitErrorNT (internal/streams/destroy.js:106:8)
  | 2021-04-26T00:25:44.202+05:00 | at emitErrorCloseNT (internal/streams/destroy.js:74:3)
  | 2021-04-26T00:25:44.202+05:00 | at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  | 2021-04-26T00:25:44.202+05:00 | errno: -3008,
  | 2021-04-26T00:25:44.202+05:00 | code: 'ENOTFOUND',
  | 2021-04-26T00:25:44.202+05:00 | syscall: 'getaddrinfo',
  | 2021-04-26T00:25:44.202+05:00 | hostname: 'redis://redis.adioone-teams.local'
  | 2021-04-26T00:25:44.202+05:00 | }
  | 2021-04-26T00:25:44.291+05:00 | npm ERR! code ELIFECYCLE
  | 2021-04-26T00:25:44.292+05:00 | npm ERR! errno 1
  | 2021-04-26T00:25:44.295+05:00 | npm ERR! backend@0.0.0 development: `NODE_ENV=development node ./bin/www`
  | 2021-04-26T00:25:44.295+05:00 | npm ERR! Exit status 1
  | 2021-04-26T00:25:44.295+05:00 | npm ERR!
  | 2021-04-26T00:25:44.295+05:00 | npm ERR! Failed at the backend@0.0.0 development script.
  | 2021-04-26T00:25:44.296+05:00 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  | 2021-04-26T00:25:44.301+05:00 | npm ERR! A complete log of this run can be found in:
  | 2021-04-26T00:25:44.301+05:00 | npm ERR! /root/.npm/_logs/2021-04-25T19_25_44_296Z-debug.log

**Comment by kohidave** [comment]
Related issue a customer is having #2214

**Comment by mebibou** [comment]
I have exactly the same problem on one of my clusters, but strangely it works for another AWS account.

I have a Load Balanced Web service deployed:
```
About

  Application      my-app
  Name              api
  Type              Load Balanced Web Service

Configurations

  Environment       Tasks               CPU (vCPU)          Memory (MiB)        Port
  -----------       -----               ----------          ------------        ----
  production        1                   0.25                512                 80

Routes

  Environment       URL
  -----------       ---
  production        http://xxxxx.us-east-1.elb.amazonaws.com/cam

Service Discovery

  Environment       Namespace
  -----------       ---------
  production       api.my-app.local:80

Variables

  Name                                Container           Environment         Value
  ----                                ---------           -----------         -----
  COPILOT_APPLICATION_NAME              "                   "                 my-app
  COPILOT_ENVIRONMENT_NAME              "                   "                 production
  COPILOT_LB_DNS                        "                   "                 xxxx.us-east-1.elb.amazonaws.com
  COPILOT_SERVICE_DISCOVERY_ENDPOINT    "                   "                 my-app.local
  COPILOT_SERVICE_NAME                  "                   "                api
  REDIS_URL                             "                   "                 redis://redis.my-app.local:6379
```

And redis as backend service:
```
About

  Application       my-app
  Name              redis
  Type              Backend Service

Configurations

  Environment       Tasks               CPU (vCPU)          Memory (MiB)        Port
  -----------       -----               ----------          ------------        ----
  production        1                   0.25                512                 6379

Service Discovery

  Environment       Namespace
  -----------       ---------
  production        redis.my-app.local:6379

Variables

  Name                                Container           Environment         Value
  ----                                ---------           -----------         -----
  COPILOT_APPLICATION_NAME            redis               production          my-app
  COPILOT_ENVIRONMENT_NAME              "                   "                 production
  COPILOT_SERVICE_DISCOVERY_ENDPOINT    "                   "                 my-app.local
  COPILOT_SERVICE_NAME                  "                   "                 redis
```
When I look at the records on Route53, `redis.my-app.local` is present. But then the logs in my api always say:
```
uncaughtException: Redis connection to redis.my-app.local:6379 failed - getaddrinfo ENOTFOUND redis.my-app.local
```

Then at some point redis shuts down because there is no incoming connection... what is the issue?

**Comment by efekarakus** [comment]
Hi @mebibou !

That's really strange, I don't see anything that seems problematic in the `copilot svc show` outputs above 🤔 

To test out connections, maybe we can try the following steps:
* `copilot svc exec` into the redis service and see if `curl -w '\n' localhost:6379/ping` seems to work fine to ensure the service is healthy
* `copilot svc exec` into the api service and `curl -w '\n' http://redis.my-app.local:6379/ping` to see if indeed we can replicate the connection issue.

By default both services should share a security group `EnvironmentSecurityGroup` that allows ingress from itself so they should be able to communicate with each other 💭

**Comment by mebibou** [comment]
On the api service:
```
Starting session with SessionId: ecs-execute-command-000f96e72d4bd5072
# curl -w '\n' http://redis.my-app.local:6379/ping

curl: (6) Could not resolve host: redis.my-app.local
```
On Redis:
```
# curl -w '\n' localhost:6379/ping
/bin/sh: 1: curl: not found
```

Should I check anything about the ingress as well?

**Comment by efekarakus** [comment]
ok cool! At least it looks like it's the due to the server code in the "api" service. Would you mind checking the security groups in both services and ensuring that the same security group is present for both services?

Do you remember if any configuration was manually modified for either services or were all changes done through copilot?

**Comment by mebibou** [comment]
@efekarakus I think its a problem with Service discovery. I checked the IP that was associated with redis container and tried to ping it:
```
# curl -w '\n' http://172.31.2.182:6379/ping

curl: (52) Empty reply from server
```
while using the `.local` version still says ` Could not resolve host`

Also, I have 2 web balanced services deployed, and I can ping them between containers using their private IPs, but none of the pings work using the local address

**Comment by mebibou** [comment]
@efekarakus ok I found the issue, `DNS hostnames` was not enabled on the VPC... I think it would be good to either a) enable it while using copilot or b) warn the user that it's not on so Hosted Zones will not resolve!

**Comment by efekarakus** [comment]
oh wow great find! I assume this meant that the VPC was imported? because the copilot generated VPC does have:
```yaml
    EnableDnsHostnames: true
    EnableDnsSupport: true
```

**Comment by mebibou** [comment]
it was an existing VPC. I think this is the most common case no?
