### ISSUE TITLE
How to migrate a database by the copilot job for Load Balanced Service

### ISSUE THREAD

**Issue by phasetr** [aws/copilot-cli#4579]
My small sample project is [here](https://github.com/phasetr/AWS-samples/tree/main/copilot-django-load-balanced).

I want to migrate a database by the copilot job for development. I can run migration by `copilot svc exec`, but, for simplicity, I want to run it by `copilot job` (or `copilot task`).

I created a job `migrate` in the above sample, then I had an error, "the environment variable MYDJANGODB_SECRET is not defined", so I set a secret in the yaml. Then I could not connect to server. The below is the error message.

```
2023-03-04T08:58:54.733+09:00	dbsecret is not None!
2023-03-04T08:58:54.733+09:00	# Here we have a dbsecret json string for check
2023-03-04T09:01:06.001+09:00	Traceback (most recent call last):
2023-03-04T09:01:06.001+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-03-04T09:01:06.002+09:00	    self.connect()
2023-03-04T09:01:06.002+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.002+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.002+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.002+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-03-04T09:01:06.002+09:00	    self.connection = self.get_new_connection(conn_params)
2023-03-04T09:01:06.002+09:00	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.002+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.002+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.002+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.002+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-03-04T09:01:06.002+09:00	    connection = Database.connect(**conn_params)
2023-03-04T09:01:06.002+09:00	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.002+09:00	  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
2023-03-04T09:01:06.002+09:00	    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-03-04T09:01:06.003+09:00	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.003+09:00	psycopg2.OperationalError: could not connect to server: Connection timed out
2023-03-04T09:01:06.003+09:00		Is the server running on host "I-rewrite-here-for-security.us-west-2.rds.amazonaws.com" (10.0.2.4) and accepting
2023-03-04T09:01:06.003+09:00		TCP/IP connections on port 5432?
2023-03-04T09:01:06.003+09:00	The above exception was the direct cause of the following exception:
2023-03-04T09:01:06.003+09:00	Traceback (most recent call last):
2023-03-04T09:01:06.003+09:00	  File "/code/manage.py", line 22, in <module>
2023-03-04T09:01:06.003+09:00	    main()
2023-03-04T09:01:06.003+09:00	  File "/code/manage.py", line 18, in main
2023-03-04T09:01:06.003+09:00	    execute_from_command_line(sys.argv)
2023-03-04T09:01:06.003+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
2023-03-04T09:01:06.003+09:00	    utility.execute()
2023-03-04T09:01:06.003+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
2023-03-04T09:01:06.003+09:00	    self.fetch_command(subcommand).run_from_argv(self.argv)
2023-03-04T09:01:06.003+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
2023-03-04T09:01:06.003+09:00	    self.execute(*args, **cmd_options)
2023-03-04T09:01:06.003+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
2023-03-04T09:01:06.003+09:00	    output = self.handle(*args, **options)
2023-03-04T09:01:06.004+09:00	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 89, in wrapped
2023-03-04T09:01:06.004+09:00	    res = handle_func(*args, **kwargs)
2023-03-04T09:01:06.004+09:00	          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 75, in handle
2023-03-04T09:01:06.004+09:00	    self.check(databases=[database])
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 419, in check
2023-03-04T09:01:06.004+09:00	    all_issues = checks.run_checks(
2023-03-04T09:01:06.004+09:00	                 ^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 76, in run_checks
2023-03-04T09:01:06.004+09:00	    new_errors = check(app_configs=app_configs, databases=databases)
2023-03-04T09:01:06.004+09:00	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
2023-03-04T09:01:06.004+09:00	    errors.extend(model.check(**kwargs))
2023-03-04T09:01:06.004+09:00	                  ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.004+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1303, in check
2023-03-04T09:01:06.005+09:00	    *cls._check_indexes(databases),
2023-03-04T09:01:06.005+09:00	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.005+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1695, in _check_indexes
2023-03-04T09:01:06.005+09:00	    connection.features.supports_covering_indexes or
2023-03-04T09:01:06.005+09:00	    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.005+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
2023-03-04T09:01:06.005+09:00	    res = instance.__dict__[self.name] = self.func(instance)
2023-03-04T09:01:06.005+09:00	                                         ^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.006+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/features.py", line 92, in is_postgresql_11
2023-03-04T09:01:06.007+09:00	    return self.connection.pg_version >= 110000
2023-03-04T09:01:06.007+09:00	           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 48, in __get__
2023-03-04T09:01:06.007+09:00	    res = instance.__dict__[self.name] = self.func(instance)
2023-03-04T09:01:06.007+09:00	                                         ^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
2023-03-04T09:01:06.007+09:00	    with self.temporary_connection():
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
2023-03-04T09:01:06.007+09:00	    return next(self.gen)
2023-03-04T09:01:06.007+09:00	           ^^^^^^^^^^^^^^
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
2023-03-04T09:01:06.007+09:00	    with self.cursor() as cursor:
2023-03-04T09:01:06.007+09:00	         ^^^^^^^^^^^^^
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.007+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.007+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.007+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 259, in cursor
2023-03-04T09:01:06.008+09:00	    return self._cursor()
2023-03-04T09:01:06.008+09:00	           ^^^^^^^^^^^^^^
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 235, in _cursor
2023-03-04T09:01:06.008+09:00	    self.ensure_connection()
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.008+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.008+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 218, in ensure_connection
2023-03-04T09:01:06.008+09:00	    with self.wrap_database_errors:
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 90, in __exit__
2023-03-04T09:01:06.008+09:00	    raise dj_exc_value.with_traceback(traceback) from exc_value
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
2023-03-04T09:01:06.008+09:00	    self.connect()
2023-03-04T09:01:06.008+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.008+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.009+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.009+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/base.py", line 200, in connect
2023-03-04T09:01:06.009+09:00	    self.connection = self.get_new_connection(conn_params)
2023-03-04T09:01:06.009+09:00	                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.009+09:00	  File "/usr/local/lib/python3.11/site-packages/django/utils/asyncio.py", line 33, in inner
2023-03-04T09:01:06.009+09:00	    return func(*args, **kwargs)
2023-03-04T09:01:06.009+09:00	           ^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.009+09:00	  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
2023-03-04T09:01:06.009+09:00	    connection = Database.connect(**conn_params)
2023-03-04T09:01:06.009+09:00	                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.009+09:00	  File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
2023-03-04T09:01:06.009+09:00	    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2023-03-04T09:01:06.009+09:00	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-03-04T09:01:06.009+09:00	django.db.utils.OperationalError: could not connect to server: Connection timed out
2023-03-04T09:01:06.009+09:00		Is the server running on host "I-rewrite-here-for-security.us-west-2.rds.amazonaws.com" (10.0.2.4) and accepting
2023-03-04T09:01:06.009+09:00		TCP/IP connections on port 5432?
```

(The secret value is not wrong, I think.) Why can I connect to the db server? Should I set some security group settings?

Furthermore, I have one simple question. WHat is the best practice for "production" database migration? I will set a `copilot pipeline` for staging and production.

**Comment by efekarakus** [comment]
Hi @phasetr !

> (The secret value is not wrong, I think.) Why can I connect to the db server? Should I set some security group settings?
I can see that the manifest looks like this:
```yaml
secrets:
  MYDJANGODB_SECRET:
    secretsmanager: 'mydjangodbAuroraSecret-ObSZ2fGHWHTm'
```
So I'm assuming the secret was not created with `copilot secret init`. Is that correct?

While [bringing your own secrets](https://aws.github.io/copilot-cli/docs/developing/secrets/#bring-your-own-secrets) to Copilot, the secrets need to be tagged with `copilot-application` and `copilot-environment` so that the task has permission to access the resource.

Do the AWS tags exist in the secrets manager secret? 
Check out this guide hopefully that will help illustrate how to integrate with secrets: https://aws.github.io/copilot-cli/docs/developing/secrets/#in-secrets-manager 

> WHat is the best practice for "production" database migration? I will set a copilot pipeline for staging and production.

I believe your concern is related to this issue: https://github.com/aws/copilot-cli/issues/3007, for now as a mitigation this comment might be able to help: https://github.com/aws/copilot-cli/issues/2992#issuecomment-964654705.

Hope this helps!

**Comment by phasetr** [comment]
@efekarakus Thank you for your comment!

>So I'm assuming the secret was not created with copilot secret init. Is that correct?

This is correct. The value is auto generrated by `copilot storage init`, not `copilot secret init`. I'll check your answer carefully, and I will ask more questions when I have some more problems.

**Comment by phasetr** [comment]
@efekarakus 
I checked the [link](https://aws.github.io/copilot-cli/docs/developing/secrets/#bring-your-own-secrets), and then, in Secrets Manager, I have tags and the secret database values probably due to `copilot storage init`. Furthermore I can get a database info and the log tells `connection timed out`, so I guess I have some security issue. So I added the following to the job yml.

```
network:
  vpc:
    placement: private
    security_group: ["sg-06b688b20ec765960"]
```

The above security group is from RDS, `copilot-mydjango-test-django-web-Aurora`: this is the proper security group, I think. However I have still `connection timed out`. What do I do to solve the connection timed out?

**Comment by phasetr** [comment]
Service itself can access database, but jobs' accesses timed out. Hence I suspect job settings.

**Comment by phasetr** [comment]
When I check `copilot svc package` and `copilot job package --name migrate`, then I find the follwoing difference.

```
      ContainerDefinitions:
        - Name: !Ref WorkloadName
          Image: !Ref ContainerImage
          Secrets:
            - Name: MYDJANGODB_SECRET
              ValueFrom:
                Fn::GetAtt: [AddonsStack, Outputs.mydjangodbSecret]
          Environment:
            - Name: COPILOT_APPLICATION_NAME
              Value: !Sub '${AppName}'
            - Name: COPILOT_SERVICE_DISCOVERY_ENDPOINT
              Value: test.mydjango.local
            - Name: COPILOT_ENVIRONMENT_NAME
              Value: !Sub '${EnvName}'
            - Name: COPILOT_SERVICE_NAME
              Value: !Sub '${WorkloadName}'
            - Name: MYDJANGODB_SECURITY_GROUP                              # HERE
              Value:                                                       # HERE
                Fn::GetAtt: [AddonsStack, Outputs.mydjangodbSecurityGroup] # HERE
            - Name: COPILOT_LB_DNS
              Value: !GetAtt EnvControllerAction.PublicLoadBalancerDNSName
```

`svc` has `MYDJANGODB_SECURITY_GROUP` but job does not. I try to add this to job.

**Comment by phasetr** [comment]
What do I write the part `Fn::GetAtt: [AddonsStack, Outputs.mydjangodbSecurityGroup]` in a job manifest file?

**Comment by efekarakus** [comment]
> I checked the [link](https://aws.github.io/copilot-cli/docs/developing/secrets/#bring-your-own-secrets), and then, in Secrets Manager, I have tags and the secret database values probably due to copilot storage init. Furthermore I can get a database info and the log tells connection timed out, so I guess I have some security issue. So I added the following to the job yml.

Oh apologies I get it now! 🙇 This is my bad I missed your message earlier that mentioned that the secret value passed in is correct so I was looking at the wrong place.

OK yes your intuition is definitely correct with the following change:
```yaml
network:
  vpc:
    placement: private
    security_group: ["sg-06b688b20ec765960"]
```

However, I don't think it's needed. All the ECS tasks created with copilot automatically get added to a security group called the Environment Security Group. Would you mind updating your database addon's security group here:
https://github.com/phasetr/AWS-samples/blob/5cedae2b56282b3d2440310b0ad8801425b5fc66/copilot-django-load-balanced/copilot/django-web/addons/mydjango-db.yml#L35-L46

with the following change:
```yaml
  mydjangodbSecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the Aurora Serverless v2 cluster mydjangodb'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'The Security Group for ${Name} to access Aurora Serverless v2 cluster mydjangodb.'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
      # NEW FIELD HERE.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: { 'Fn::ImportValue': !Sub '${App}-${Env}-EnvironmentSecurityGroup' }
          Description: 'Access to environment security group'
      # END OF NEW FIELD
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-${Name}-Aurora'
```
The snippet allow will grant access to all ECS tasks within the environment to the database.

Hope this helps!

**Comment by phasetr** [comment]
Thank you for your comment! And I'm sorry for my unclear comment.

Since I still have the `connection timed out`, I'll ask some questions to you.

I [added the description](https://github.com/phasetr/AWS-samples/commit/3d8c74832786529661f4d04d35a1a614d41aafa4) in the `mydjango-db.yml`, and once I deleted network description in a job yml. I ran `copilot svc deploy`, `copilot job deploy`, and `copilot job run`. Do I need network description in a job yaml? Or some more description?

**Comment by efekarakus** [comment]
Hi @phasetr ! I'm so sorry I told you the wrong security group name to add the Ingress 😓 

It should have been to add it to `mydjangodbDBClusterSecurityGroup` instead of `mydjangodbSecurityGroup`.

So like this:
```yaml
SecurityGroupIngress:
   - ToPort: 5432
     FromPort: 5432
     IpProtocol: tcp
     Description: !Sub 'From the Aurora Security Group of the workload ${Name}.'
     SourceSecurityGroupId: !Ref mydjangodbSecurityGroup
   - IpProtocol: tcp
     FromPort: 5432
     ToPort: 5432
     SourceSecurityGroupId: { 'Fn::ImportValue': !Sub '${App}-${Env}-EnvironmentSecurityGroup' }
     Description: 'Access to environment security group'
```

Can you try doing `copilot svc deploy` after saving the edit and then `copilot job run` again 🙏 Apologies for the back and forth

**Comment by phasetr** [comment]
@efekarakus Thank you for comments, and I can finally migrate database from jobs! The setting is also useful for Request-Driven service.

I added the [README](https://github.com/phasetr/AWS-samples/blob/main/README.md) in my repository and summarize description.

I close this issue since your help solves my problem. Thank you again for your time!
