### ISSUE TITLE
Confusing typo in the docs

### ISSUE THREAD

**Issue by tegryan-ggs** [aws/copilot-cli#5712]
There is an omission in the docs which leads to a ruby error in the pipeline.  The example code given here:  https://aws.github.io/copilot-cli/docs/manifest/pipeline/

```
build:
  additional_policy:
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
          Resource: '*'
```

should be

```
build:
  additional_policy:
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action:
            - ecr:GetAuthorizationToken
          Resource: '*'
```

Otherwise you will get a ruby error like:

```
[Container] 2024/03/07 01:15:52.854860 Running command pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipelines/qa-priv-envs/manifest.yml \| ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
--
64 | /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
65 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/class_loader.rb:28:in `load'
66 | from (eval):2:in `date'
67 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/scalar_scanner.rb:66:in `tokenize'
68 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:65:in `deserialize'
69 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:130:in `visit_Psych_Nodes_Scalar'
70 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
71 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
72 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:35:in `accept'
73 | from /root/.rbenv/versions/3.2.2/lib/ruby/3.2.0/psych/visitors/to_ruby.rb:347:in `block in revive_hash'
...
```

**Comment by iamhopaul123** [comment]
Hello @tegryan-ggs. Sorry for the confusion and thank you for calling that out! Will send out a fix soon.
