### ISSUE TITLE
panic on bad selection for pipeline repo

### ISSUE THREAD

**Issue by SoManyHs** [aws/copilot-cli#667]
I mistakenly typed a letter that did not match any of the possible github repos and then deleted it. pressing enter resulted in a segfault:
```
~/aws-reinvent-2019-trivia-backend(master)$ ecs-preview pipeline init

? Would you like to add an environment to your pipeline? Yes

? Which environment would you like to add to your pipeline? test

? Which GitHub repository would you like to use for your application?  [Use arrows to move, type to filter, ? for more help]
  git@github.com:SoManyHs/aws-reinvent-trivia-2019-backend
  https://github.com/aws-samples/aws-reinvent-2019-trivia-game
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/AlecAivazis/survey/v2.(*Select).Prompt(0xc0001d76c0, 0xc000502048, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.0.5/select.go:304 +0x9ee
github.com/AlecAivazis/survey/v2.Ask(0xc000135a88, 0x1, 0x1, 0x1a66640, 0xc0002e0600, 0xc0002e0620, 0x2, 0x2, 0x1a94f40, 0x1cd6001)
	/Users/hsinghui/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.0.5/survey.go:278 +0x557
github.com/AlecAivazis/survey/v2.AskOne(0x1f055c0, 0xc0001d76c0, 0x1a66640, 0xc0002e0600, 0xc0002e0620, 0x2, 0x2, 0x0, 0x4)
	/Users/hsinghui/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.0.5/survey.go:221 +0xc1
github.com/aws/amazon-ecs-cli-v2/internal/pkg/term/prompt.Prompt.SelectOne(0x1cd5fc0, 0x1cbcc3f, 0x43, 0x1cc116a, 0xea, 0xc000524120, 0x2, 0x2, 0x0, 0xc000245001, ...)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/term/prompt/prompt.go:129 +0x1fb
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.(*initPipelineOpts).selectGitHubURL(0xc000245040, 0x0, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/pipeline_init.go:385 +0x8d
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.(*initPipelineOpts).Ask(0xc000245040, 0x0, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/pipeline_init.go:160 +0x17f
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.BuildPipelineInitCmd.func1(0xc0002a6780, 0x26a9a08, 0x0, 0x0, 0xc00014dd30, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/pipeline_init.go:494 +0xc4
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.runCmdE.func1(0xc0002a6780, 0x26a9a08, 0x0, 0x0, 0x0, 0x0)
	/Users/hsinghui/workspace/amazon-ecs-archer/internal/pkg/cli/cli.go:105 +0x72
github.com/spf13/cobra.(*Command).execute(0xc0002a6780, 0x26a9a08, 0x0, 0x0, 0xc0002a6780, 0x26a9a08)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000288000, 0x0, 0x0, 0xc0000440b8)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/hsinghui/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/hsinghui/workspace/amazon-ecs-archer/cmd/ecs-preview/main.go:25 +0x27
```

**Comment by efekarakus** [comment]
We haven't seen a segfault with the selector package in a long time, resolving the issue due to stateleness
